Sprint 1/step 1
Grione/react-burger pull request #1
Opened 2023-01-04 08:35 UTC by Grione

2023-01-04 09:40 UTC, ArslanDev666 commented on src/components/app/App.jsx
> +class App extends React.Component {
**Можно лучше:**

Используйте функциональные компоненты, а не классовые. Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

2023-01-04 09:42 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +          />
**Надо исправить:**

Булки должны быть из моковых данных, а когда будет финальный этап задания то все данные будут приходить с сервера. 

Оптимальный способ для получения булки использовать find по типу `bun`.

2023-01-04 09:43 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        </ul>
**Надо исправить:**

Ингредиенты должны быть из моковых данных, а когда будет финальный этап задания то все данные будут приходить с сервера. 

Оптимальный способ для получения ингредиентов **(Без булок)** использовать метод filter.

2023-01-04 09:45 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const sauce = props.data.filter((el) => el.type === 'sauce');
**Вы молодец!**

Отличное решение для разделения ингредиентов.

2023-01-04 10:03 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;

### **Но есть несколько замечаний, которые нужно исправить:**

- Используйте моковые данные (burgerConstructor), а не статичные.

- В компонентах у которых есть пропсы, необходимо описать propTypes. Не забудьте указывать `.isRequired`, без этого не контролируется, что пропс передается.
  
- Необходимо описать полную структуру ингредиента, и потом её переиспользовать.
  Не забывайте указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:
  
  ```js
  // когда вы передаёте массив ингредиентов
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  // когда вы передаёте 1 ингредиент
  data: ingredientTypes.isRequired;
  ```

### **Сделает код лучше:**

- Используйте функциональные компоненты, а не классовые. Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)


### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/app/App.jsx
> +class App extends React.Component {
**Можно лучше:**

Используйте функциональные компоненты, а не классовые. Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +          />
**Надо исправить:**

Булки должны быть из моковых данных, а когда будет финальный этап задания то все данные будут приходить с сервера. 

Оптимальный способ для получения булки использовать метод find по типу `bun`.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/find

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-constructor/burger-constructor.jsx
> +        </ul>
**Надо исправить:**

Ингредиенты должны быть из моковых данных, а когда будет финальный этап задания то все данные будут приходить с сервера. 

Оптимальный способ для получения ингредиентов **(Без булок)** использовать метод filter.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  const sauce = props.data.filter((el) => el.type === 'sauce');
**Вы молодец!**

Отличное решение для разделения ингредиентов.

Единственное, названия нужно указывать в множ.числе `buns, main, и т.п` т.к. у вас массив элементов

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/app/App.jsx
> +    this.state = { DATA };
**Можно лучше:** 

Немного не понимаю, зачем тут создавать стейт из data.

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +function BurgerIngredients(props) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

и используйте деструктуризацию пропсов.

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        <li><Tab>Булки</Tab></li>
**Можно лучше:**

По макету хотя бы 1 таб должен быть активным, а лучше всего сделать их переключение по клику)

В будущем нужно будет реализовать скролл список ингредиентов к нужному разделу, при клике на таб.

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-ingredients-card/burger-ingredients-card.jsx
> +function BurgerIngredientsCard(props) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-01-04 10:03 UTC, ArslanMustafin commented on src/components/burger-ingredients-list/burger-ingredients-list.jsx
> +function BurgerIngredientsList(props) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-01-10 02:24 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Приступайте к выполнению финального этапа задания.**

- Практически все замечания с прошлого ревью были исправлены.

### **Но есть несколько замечаний, которые нужно исправить:**

- В компонентах у которых есть пропсы, необходимо описать propTypes. Не забудьте указывать `.isRequired`, без этого не контролируется, что пропс передается.

- Необходимо описать полную структуру ингредиента, и потом её переиспользовать.
  Не забывайте указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  // когда вы передаёте массив ингредиентов
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  // когда вы передаёте 1 ингредиент
  data: ingredientTypes.isRequired;
  ```

### **Сделает код лучше:**

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2023-01-10 02:24 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +function BurgerConstructor(props) {
**Надо исправить:**

Для этого компонента так же нужно описать PropTypes.

2023-01-10 02:24 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  data: PropTypes.arrayOf(PropTypes.object.isRequired).isRequired,
**Надо исправить:**

Требуется полное описание структуры ингредиента, а не propTypes.object.

2023-01-10 02:24 UTC, ArslanDev666 commented on src/components/burger-ingredients-card/burger-ingredients-card.jsx
> +  card: PropTypes.shape({
**Надо исправить**

во многих компонентах будет повторяться описание PropTypes ингредиента
Следует вынести его в отдельный файл (можно создать файл prop-types.js в папке utils) и переиспользовать описание пропсов ингрединта, а не дублировать. А также не забывайте про `isRequired`.

2023-01-10 02:24 UTC, ArslanDev666 commented on src/components/burger-ingredients-list/burger-ingredients-list.jsx
> +  ingredients: PropTypes.arrayOf(PropTypes.object),
**Надо исправить:**

Необходимо описать полную структуру ингредиента, и потом её переиспользовать.
Не забывайте указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:
  
```js
  // когда вы передаёте массив ингредиентов
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  // когда вы передаёте 1 ингредиент
  data: ingredientTypes.isRequired;
```

2023-01-10 02:25 UTC, ArslanDev666 approved these changes

2023-01-10 13:26 UTC, merged